### ISSUE TITLE
autostart feature

### ISSUE THREAD

**Issue by exciar** [Mefgner/Smart-Refresh-Rate#3]
title

**Comment by Mefgner** [comment]
?
It's already implemented.

**Comment by exciar** [comment]
when I install it somehow it doesn't autostart, but the refresh rate switching works, I had to use Scheduled Tasks to make it work on my machine so it runs every time I start the computer

**Comment by Mefgner** [comment]
oh, so how made it: when start the program it checks if is there another version of this program (if yes kills and reinstalls then launches from %localappdata%\SRR folder) and then adds itself to autostart and does his magic in background (**It doesn't have any kind of UI**). If you don't want this prog to autostart just disable in task scheduler.
